### ISSUE TITLE
build时下载不到jar包

### ISSUE THREAD

**Issue by tearsknow** [xuuhaoo/Android-DefenseCrash#7]
Could not download defense_crash.aar (com.tonystark.android:defense_crash:2.0.0)

Could not get resource 'https://dl.bintray.com/xuuhaoo/maven/com/tonystark/android/defense_crash/2.0.0/defense_crash-2.0.0.aar'.
> Could not GET 'https://dl.bintray.com/xuuhaoo/maven/com/tonystark/android/defense_crash/2.0.0/defense_crash-2.0.0.aar'. Received status code 403 from server: Forbidden

**Comment by tearsknow** [comment]
Could not download defense_crash.aar (com.tonystark.android:defense_crash:2.0.0)
 > Could not get resource 'https://dl.bintray.com/xuuhaoo/maven/com/tonystark/android/defense_crash/2.0.0/defense_crash-2.0.0.aar'.
    > Could not GET 'https://dl.bintray.com/xuuhaoo/maven/com/tonystark/android/defense_crash/2.0.0/defense_crash-2.0.0.aar'. Received status code 403 from server: Forbidden

**Comment by tearsknow** [comment]
上午时可以用，下午就用不了了，是不是现在不能用了，有什么解决办法吗

**Comment by xuuhaoo** [comment]
已经迁移到jitpack了. 可以正常使用了
